
---
- name: Testing lookup functions
  hosts: localhost
  vars:
   present_dir: " {{ lookup('env', 'PWD') }}"
   user: " {{ lookup('env', 'USER') }}"
  vars_files: [./testvars.yml]
  tasks:
   - debug:
      msg: "This is env variable {{ item }}"
     loop:
      - "{{ present_dir }}"
      - "{{ user }}"
   - debug: 
      msg: "{{ lookup('env','MYNAME') | default('SaiKiraN',true)}}"
   - file:
      name: "{{ item.name}}"
      state: "{{ item.state}}"
      mode: "{{item.mode | default(omit)}}"
     loop: "{{ files }}"
     tags: 
      - file 
   - user:
      name: "{{item.name}}"
      shell: "{{item.shell | default(omit)}}"
      state: "{{item.state | default('absent')}}"
     loop: "{{ users}}"
     become: true
     tags: 
      - user
   - set_fact:
      fruit: []
     tags:
      - sp
   - set_fact:
      fruit: "{{ fruit + [ item.split('@')[0] ] }}"
     loop: "{{fruits}}"
     tags:
      - sp
   - debug:
      msg: "{{ fruit }}"
     tags:
      - sp
